### ISSUE TITLE
Create API calls counters

### ISSUE THREAD

**Issue by crimaniak** [alkulsv/mytesthub#1]
Make new API to see how many times called any API from server start

**Comment by crimaniak** [comment]
1. get task
2. learn how to make commit linked to issue on github
3. create new branch
4. write code
5. functional test
6. merge to main branch

**Comment by alkulsv** [comment]
1. ok
2. Just add fix#1 (number of issue) in the comment to the commit
3. NewApi7Version branch added.
4. Code is updated.
5. Test is ok.
6. how to make merge?

**Comment by crimaniak** [comment]
Need to recreate branch from current master branch and then move all commits from NewApi7Version branch to it.
additional problems and remarks:
- no issue number in new branch name;
- no issue number in commits;
- in the case of correct git actions merge will be completed without conflcts;
- issue is not completed and must not be closed yet. Please open it again.
