### ISSUE TITLE
Test service requesting APIs in N streams

### ISSUE THREAD

**Issue by crimaniak** [alkulsv/mytesthub#3]
- Create test suite capable to multiple requests to service at a time with custom parameters.
- Use this application to check if API counters works as expected.

How to check counters:
- Get counters using API
- Run many requests in many streams, for example 20 streams by 100 request each for some service.
- Get counters again and check if service counter increased as expected (for example for 2000).

It's possible to resovle this task with only OS scripts (bash or WSH depending on OS) and Apache ab utility: http://httpd.apache.org/docs/2.2/programs/ab.html

**Comment by alkulsv** [comment]
Сommit b556487251d5317dd034d7f89c5c64c76e0f6f42
issue #3 update.
1. New API8 added. It is return total counter of request for all APIs.
2. New folder TestScripts/ added to collect all test scripts.
3. WHS script TesRequestScript.vbs added. It make 2000 requests in 20 streams
   to check HttpServer. It will show total finished requests in the test.

PS TesRequestScript.vbs use appache ab utility.
